[env:digispark-tiny]
platform = atmelavr
board = digispark-tiny
# This flag optimizes for size to fit the 8KB limit
build_flags = -Os -Wall
# This is the protocol for the Digispark USB upload
upload_protocol = micronucleus
